#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Sorry for this! set this to your own jdk version 21 path
#To-do: figure out how to not have this
#org.gradle.java.home=/home/joey/.jdks/ms-21.0.12.1

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
